DIVIDER=----------------------------------------------
default:
	@(echo $(DIVIDER); cd datatypes/src; $(MAKE) -k )

clean:
	@(echo $(DIVIDER); cd datatypes/src; $(MAKE) -k clean)

test:
	@(echo $(DIVIDER); cd datatypes/src; $(MAKE) -k test)