DIVIDER=----------------------------------------------
default:
	@(echo $(DIVIDER); cd datatypes; $(MAKE) -k )

clean:
	@(echo $(DIVIDER); cd datatypes; $(MAKE) -k clean)

test:
	@(echo $(DIVIDER); cd datatypes; $(MAKE) -k test)